name: Test
on: [push]

jobs:
  test:
    name: Test
    runs-on: ubuntu-16.04
    steps:
      - uses: actions/checkout@v2
      - name: Install Dependencies
        run: yarn install --frozen-lockfile
      - name: Unit Tests
        run: yarn test:unit
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          flags: unittests
          files: ./coverage/clover.xml, ./coverage/coverage-final.json
          name: cypress-tests
      - name: E2E tests
        env: 
          VUE_APP_API_KEY: ${{ secrets.API_KEY }}
        run: yarn test:e2e --headless